version: '3'
services:
  app:
    container_name: node-postgres-server
    restart: always
    build: .
    ports:
      - '5050:5050'
    external_links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=notes
    ports:
      - '8080:8080'
